/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fusion_serv_utils_mediacodec */

#ifndef _Included_com_fusion_serv_utils_mediacodec
#define _Included_com_fusion_serv_utils_mediacodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fusion_serv_utils_mediacodec
 * Method:    G729aInitDecoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fusion_serv_utils_mediacodec_G729aInitDecoder
  (JNIEnv *, jobject);

/*
 * Class:     com_fusion_serv_utils_mediacodec
 * Method:    g729decoder
 * Signature: ([BI)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_fusion_serv_utils_mediacodec_g729decoder
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
